### PR TITLE
Update to Gulp, Dynamic Value, Restrict DOM Query

### PR DESCRIPTION
**Pull request by cdcharlebois**
+ added Gulp task runner
+ added ability to use an attribute from the context object as the `value` for the attribute being set
+ added ability to restrict DOM query (for localized changes so it doesn't affect the whole page)

### CODE REVIEW

**Comment by rik-bos** [comment]
Looks great! Have you updated the test project as well to be sure it can be released to the appstore?

**Comment by cdcharlebois** [comment]
Oops! No, I didn't update the test project. I was modifying for another project. Let me update that and I'll resubmit

**Comment by cdcharlebois** [comment]
+ Updated Test project
+ Fixed a bug where if you tried to append a value to a JS attribute like `onclick` it would fail since `function.indexOf()` is undefined

**Comment by rik-bos** [comment]
Hi Conner,

I saw that the attribute set / appended using an context object attribute
is not updated when the attribute is updated, as a user I would expect that
to happen. I'll merge the pull request and try to fix the update on
attribute change this week. Afterwards I'll deploy the new version to the
appstore.

Kind regards,
Rik

2017-01-27 15:37 GMT+01:00 Conner <notifications@github.com>:

**Pull request merged**
